<a href="https://colab.research.google.com/github/thimaporn-r/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## dictionary

สามารถindexด้วยอะไรก็ได้



index คือการชี้

In [2]:
ex_dict = { ' a ' :10, ' 1 ' :1, 'stat' :5}

In [3]:
ex_dict['stat']

5

In [8]:
ex2_dict = { 1 : 'one', 2 : 'two', 3 :'three'}

In [9]:
ex2_dict[2]

'two'

 ### การเพิ่มสมาชิก

In [10]:
ex2_dict[0] = 'zero'

In [11]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั่ง

In [12]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [13]:
for index in ex2_dict.keys():
  print(index)

1
2
3
0


In [14]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [15]:
index

0

dict เอาไปใช้ร่วมกับ Dataframe ของ pandas

# numpy array

numpy คือ package ที่ทำงานเกี่ยวกับ array ของตัวเลช (ที่มีคนเขียนขึ้นมาและนิยมใช้)

In [16]:
import numpy 

In [17]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


### การชี้ค่าใน numpy array

In [18]:
ex_2d_array[1,2]

0.3

In [22]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(len(list_x))
print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


### operations

In [24]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [25]:
ex_2d_array.shape

(2, 3)

In [26]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]


In [27]:
ex_2d_array - ex2_2d_array

array([[ 4.2,  3. ,  4.5],
       [ 9.1,  0.1, -0.7]])

คูณ

In [28]:
ex_2d_array * ex2_2d_array

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

In [ ]:
numpy.dot()

In [29]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [31]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [32]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])