<a href="https://colab.research.google.com/github/thimaporn-r/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## dictionary

สามารถindexด้วยอะไรก็ได้



index คือการชี้

In [ ]:
ex_dict = { ' a ' :10, ' 1 ' :1, 'stat' :5}

In [ ]:
ex_dict['stat']

5

In [ ]:
ex2_dict = { 1 : 'one', 2 : 'two', 3 :'three'}

In [ ]:
ex2_dict[2]

'two'

 ### การเพิ่มสมาชิก

In [ ]:
ex2_dict[0] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั่ง

In [ ]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [ ]:
for index in ex2_dict.keys():
  print(index)

1
2
3
0


In [ ]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [ ]:
index

0

dict เอาไปใช้ร่วมกับ Dataframe ของ pandas

# numpy array

numpy คือ package ที่ทำงานเกี่ยวกับ array ของตัวเลช (ที่มีคนเขียนขึ้นมาและนิยมใช้)

In [ ]:
import numpy 

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


### การชี้ค่าใน numpy array

In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(len(list_x))
print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


### operations

In [ ]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array.shape

(2, 3)

In [ ]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]


In [ ]:
ex_2d_array - ex2_2d_array

array([[ 4.2,  3. ,  4.5],
       [ 9.1,  0.1, -0.7]])

คูณ

In [ ]:
ex_2d_array * ex2_2d_array

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

In [ ]:
numpy.dot()

In [ ]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

## HW 5


เขียน function คูณ matrix  \\
แล้ว test กับ matrix ขนาด \\
(2,3) * (3,2) \\
(4,4) * (4,1) \\
(2,2) * (2,2)


In [35]:
def cal_matrix(matrix) :
  sum = mt[0]*mt[1]
  SUM = f'ผลคูณ = {sum} '
  print(SUM)



[[[4,1,2],[1,7,3]],[[8,1],[5,7],[2,3]]]

In [41]:
mt = [[4,1,2],[8,1]]

In [39]:
print(mt[0])

[[4, 1, 2], [1, 7, 3]]


In [42]:
for matrix in mt :
  cal_matrix(matrix)

TypeError: ignored

In [20]:
cal_matrix([[1,7,4],[5,6,1]])

TypeError: ignored

In [7]:
print(len(matrix))
print(matrix[1])
print(matrix[0])

2
[[8, 1], [5, 7], [2, 3]]
[[1, 7, 4], [5, 6, 1]]


In [13]:
print(list_matrix[0]*list_matrix[1])

TypeError: ignored

In [52]:
list_x = [[5.2,3.0,4],[9.1,0.1,3]]
print(len(list_x))
print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 3]
3


In [53]:
a= list_x[1][2]

In [54]:
b = list_x[0][2]

In [55]:
a*b

12