<a href="https://colab.research.google.com/github/thimaporn-r/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## dictionary

สามารถindexด้วยอะไรก็ได้



index คือการชี้

In [ ]:
ex_dict = { ' a ' :10, ' 1 ' :1, 'stat' :5}

In [ ]:
ex_dict['stat']

5

In [ ]:
ex2_dict = { 1 : 'one', 2 : 'two', 3 :'three'}

In [ ]:
ex2_dict[2]

'two'

 ### การเพิ่มสมาชิก

In [ ]:
ex2_dict[0] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

คำสั่ง

In [ ]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [ ]:
for index in ex2_dict.keys():
  print(index)

1
2
3
0


In [ ]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [ ]:
index

0

dict เอาไปใช้ร่วมกับ Dataframe ของ pandas

# numpy array

numpy คือ package ที่ทำงานเกี่ยวกับ array ของตัวเลช (ที่มีคนเขียนขึ้นมาและนิยมใช้)

In [ ]:
import numpy 

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


### การชี้ค่าใน numpy array

In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(len(list_x))
print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


### operations

In [ ]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array.shape

(2, 3)

In [ ]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]


In [ ]:
ex_2d_array - ex2_2d_array

array([[ 4.2,  3. ,  4.5],
       [ 9.1,  0.1, -0.7]])

คูณ

In [ ]:
ex_2d_array * ex2_2d_array

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

In [ ]:
numpy.dot()

In [ ]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

## HW 5


เขียน function คูณ matrix  \\
แล้ว test กับ matrix ขนาด \\
(2,3) * (3,2) \\
(4,4) * (4,1) \\
(2,2) * (2,2)


In [ ]:
import numpy 

In [ ]:
matrix23_array = numpy.array([[2,3,5],[1,8,6]])
print(matrix23_array)

[[2 3 5]
 [1 8 6]]


In [ ]:
matrix32_array = numpy.array([[7,5],[8,3],[4,2]])
print(matrix32_array)

[[7 5]
 [8 3]
 [4 2]]


In [ ]:
matrix41_array = numpy.array([[9], [8], [6], [4]])
print(matrix41_array)

[[9]
 [8]
 [6]
 [4]]


In [ ]:
matrix1_array = numpy.array([[3,8], [1,9]])
print(matrix1_array)

[[3 8]
 [1 9]]


In [ ]:
matrix2_array = numpy.array([[4,5], [2,6]])
print(matrix2_array)

[[4 5]
 [2 6]]


In [ ]:
matrix44_array = numpy.array([[7,1,3,9], [4,2,1,8], [2,1,4,1], [1,5,4,2]])
print(matrix44_array)

[[7 1 3 9]
 [4 2 1 8]
 [2 1 4 1]
 [1 5 4 2]]


In [ ]:
def cal_matrix(a,b) :
  c = [[0 for row in range(len(b[0]))] for col in range(len(a))]
  for d in range(len(a)) :
    for e in range(len(b[0])) :
      for g in range(len(b)) :
        c[d][e] += a[d][g]*b[g][e]
  sum = numpy.matrix(c)
  return sum

In [ ]:
cal_matrix(matrix23_array,matrix32_array)

matrix([[58, 29],
        [95, 41]])

In [ ]:
cal_matrix(matrix44_array,matrix41_array)

matrix([[125],
        [ 90],
        [ 54],
        [ 81]])

In [ ]:
cal_matrix(matrix1_array,matrix2_array)

matrix([[28, 63],
        [22, 59]])

[[[4,1,2],[1,7,3]],[[8,1],[5,7],[2,3]]]

In [ ]:
mt = [[4,1,2],[8,1]]

In [ ]:
print(mt[0])

[[4, 1, 2], [1, 7, 3]]


In [ ]:
for matrix in mt :
  cal_matrix(matrix)

TypeError: ignored

In [ ]:
cal_matrix([[1,7,4],[5,6,1]])

TypeError: ignored

In [ ]:
print(len(matrix))
print(matrix[1])
print(matrix[0])

2
[[8, 1], [5, 7], [2, 3]]
[[1, 7, 4], [5, 6, 1]]


In [ ]:
print(list_matrix[0]*list_matrix[1])

TypeError: ignored

In [ ]:
list_x = [[5.2,3.0,4],[9.1,0.1,3]]
print(len(list_x))
print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 3]
3


In [ ]:
a= list_x[1][2]

In [ ]:
b = list_x[0][2]

In [ ]:
a*b

12

## Zeros,ones,random

In [1]:
import numpy as np

In [2]:
np.zeros(2)

array([0., 0.])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

ones

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

matrix operation (scalar multiplication)

In [5]:
m_one=np.ones((2,3))
2*m_one

array([[2., 2., 2.],
       [2., 2., 2.]])

random

In [6]:
np.random.rand(3,2) #uniform

array([[0.30834475, 0.35167743],
       [0.45998694, 0.84693667],
       [0.61083465, 0.53890737]])

In [8]:
np.random.randn(3,2) #normal

array([[-1.37856063, -0.59443173],
       [-1.97030449,  0.71471707],
       [ 0.13677076,  1.3146048 ]])

In [9]:
np.random.choice([1,2,3,'a','b','c'])

'a'

In [10]:
np.random.choice([1,2,3,'a','b','c'],2)

array(['c', 'a'], dtype='<U21')

In [12]:
np.random.choice([1,2,3,30,28,100],size=2)

array([ 30, 100])

In [15]:
np.random.choice([1,2,3,30,28,100],size=(2,3),replace=False)

array([[  2,  30, 100],
       [ 28,   1,   3]])

In [20]:
np.random.choice([1,2,3,30,28], size=10, p=[0.1,0.2,0.4,0.2,0.1])

array([ 2,  2, 30,  3, 28,  3, 28,  3,  3,  3])

## เฉลย

In [24]:
def mat_mul(A,B):
  c = np.zeros((A.shape[0],B.shape[1]))
  return c
