<a href="https://colab.research.google.com/github/thimaporn-r/data_viz/blob/main/Python101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3.141592653589

In [ ]:
3.141592653589

3.141592653589

In [ ]:
a = 10

In [ ]:
print(a)

10


In [ ]:
b = 11.
print(b)


11.0


In [ ]:
c = "Thima"   # เราจะบอกว่าตัวแปรเป็นอักษรหรือข้อความโดยการใช้ single ' หรือ double quote "" ล้อมรอบ

print(c)

Thima


ตัวเลขที่เป็น string ไม่สามารถเอามา + - x / กับตัวเลขได้

In [ ]:
d = '10'
print(d)

10


In [ ]:
d + 1

TypeError: ignored

variable casting (การเปลี่ยนชนิดของข้อมูล)

In [ ]:
int(d) + 1

11

In [ ]:
print(a)
print(float(a))
print(str(a))

10
10.0
10


Operation (Operators +,-,*,/,%)

In [ ]:
a+b

21.0

In [ ]:
ab = a+b
print(ab)

21.0


% คือหมาย modulo

In [ ]:
5%3

2

In [ ]:
7%3

1

คำสั่ง print แบบพิเศษ (การ format string)

In [ ]:
print("ตัวแปร")

ตัวแปร


In [ ]:
print(f'% คือการหารเอาเศษ เช่น 7%3 = {7%3}') 

% คือการหารเอาเศษ เช่น 7%3 = 1


In [ ]:
print(f'% คือการหารเอาเศษ เช่น 7%3 = {7%3}  \\
        แต่\n/ คือการหารปกติ เช่น 7/3 = {7/3}   \\
        และ\n// คือการหารเอาส่วน เช่น 7//3 = {7//3}  \\
        หรือ\nใช้ int() เพื่อหารเอาส่วน เช่น int(7/3) = {int(7/3)}')

% คือการหารเอาเศษ เช่น 7%3 = 1  \        แต่
/ คือการหารปกติ เช่น 7/3 = 2.3333333333333335   \        และ
// คือการหารเอาส่วน เช่น 7//3 = 2  \        หรือ
ใช้ int() เพื่อหารเอาส่วน เช่น int(7/3) = 2


DATA STRUCTURE (โครงสร้างข้อมูล)

List คือ การเอาตัวแปรหลายๆตัวมาเรียงกัน
list สามารถสร้างได้ 2แบบ ดังนี้

แบบที่1 > square brackets

In [ ]:
list_a = []
print(list_a)

[]


In [ ]:
list_b = [1,5,'v']
print(list_b)

[1, 5, 'v']


ลำดับที่อยู่ใน list มีความสำคัญ (ลำดับใน list เริ่มจาก 0,1,2,...)

In [ ]:
list_b[0]

1

ทดลอง เพราะพิมพ์ไม่ทัน

In [ ]:
list_a = []

In [ ]:
list_b = [1,5,'v']
print(list_b)

[1, 5, 'v']


In [ ]:
list_b

1

append() เพิ่มสมาชิกใน list

In [ ]:
list_b.append('u')
print(list_b)

[1, 5, 'v', 'u']


In [ ]:
list_b.pop()

'u'

In [ ]:
list_b

[1, 5, 'v']

In [ ]:
list_b.append(list_a)
print(list_b)

[1, 5, 'v', []]


String > list of characters

In [ ]:
t = 'python is easy'
print (t)

python is easy


In [ ]:
t = 'python is easy'
t

'python is easy'

In [ ]:
len(list_b)


4

In [ ]:
len(t)

14

access a member of a list (list&string)

โดยการเริ่มนับจะเริ่มนับจาก 0
0 คือสมาชิกตัวแรก , -1 คือสมาชิกตัวสุดท้าย

In [ ]:
t[1]

'y'

In [ ]:
t[-4]

'e'

In [ ]:
print(t[-2])

s


In [ ]:
t = 'python is easy'

### ตัวที่อยู่ข้างใน [ ] เราเรียกว่า index (ตัวชี้)

In [ ]:
t = 'python is easy'

### list slicing สามารถทำได้โดยใช้ colon :
[a:b] -> [a,b)

In [ ]:
print(t)
print(t[7:9])

python is easy
is


In [ ]:
print(t)
print(t[:6])
print(t[10:])
print(t[-4:])
print(t[:])

python is easy
python
easy
easy
python is easy


In [ ]:
print(t[::2])

pto ses


In [ ]:
print(list(range(10)))
print(list(range(10))[::2])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]


In [ ]:
print(t[2::2])

to ses


### เราสามารถเอาlistมาต่อกันได้ด้วย+

In [ ]:
t + '??'

'python is easy??'

In [ ]:
t + list_a

TypeError: ignored

การแบ่ง string ตามสัญลักษณ์ที่กำหนด -> split string

In [ ]:
t.split(' ')

['python', 'is', 'easy']

In [ ]:
time = '12:30:12'
time.split(' ')

['12:30:12']

In [ ]:
time.split(':')

['12', '30', '12']

In [ ]:
t_sp = t.split(' ')
print(t_sp)

['python', 'is', 'easy']


In [ ]:
## วิธีรวมกลับ

print(':'.join(t_sp))

python:is:easy


## HW คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม) \\
12:30:15

13:41:07

12:53:15

00:59:25

11:11:11

16:06:09

HW 2 \\
โดยที่ \\
1 ชั่วโมง = 3600 วินาที \\
1 นาที = 60 วินาที

## ข้อ 1 12:30:15

In [ ]:
time1 = '12:30:15'
time1.split(':')
list_a = time1.split(':')
print(list_a)

['12', '30', '15']


In [ ]:
list_a[0] 
int(list_a[0]) * 3600

43200

In [ ]:
A = int(list_a[0]) * 3600

In [ ]:
list_a[1] 
int(list_a[1]) * 60

1800

In [ ]:
B = int(list_a[1]) * 60

In [ ]:
list_a[2]
c = list_a[2]
print(c)

15


In [ ]:
A+B+int(c)

45015

ตอบ 12:30:15 มี 45,015 วินาที

## ข้อ 2 13:41:07

In [ ]:
time2 = '13:41:07'
time2.split(':')
list_b = time2.split(':')
print(list_b)

['13', '41', '07']


In [ ]:
list_b[0] 
int(list_b[0]) * 3600

46800

In [ ]:
A = int(list_b[0]) * 3600

In [ ]:
list_b[1] 
int(list_b[1]) * 60

2460

In [ ]:
B = int(list_b[1]) * 60

In [ ]:
list_b[2]
c = list_b[2]
print(c)

07


In [ ]:
A+B+int(c)

49267

ตอบ 13:41:07 มี 49,267 วินาที

## ข้อ 3 12:53:15

In [ ]:
time3 = '12:53:15'
time3.split(':')
list_c = time3.split(':')
print(list_c)

['12', '53', '15']


In [ ]:
list_c[0] 
int(list_c[0]) * 3600

43200

In [ ]:
A = int(list_c[0]) * 3600

In [ ]:
list_c[1] 
int(list_c[1]) * 60

3180

In [ ]:
B = int(list_c[1]) * 60

In [ ]:
list_c[2]
c = list_c[2]
print(c)

15


In [ ]:
A+B+int(c)

46395

ตอบ 12:53:15 มี 46,395 วินาที

## ข้อ 4 00:59:25

In [ ]:
time4 = '00:59:25'
time4.split(':')
list_d = time4.split(':')
print(list_d)

['00', '59', '25']


ไม่คิดหน่วยเวลาที่เป็นชั่วโมง เพราะ เท่ากับ 0

In [ ]:
list_d[1] 
int(list_d[1]) * 60

3540

In [ ]:
B = int(list_d[1]) * 60

In [ ]:
list_d[2]
c = list_d[2]
print(c)

25


In [ ]:
B+int(c)

3565

ตอบ 00:59:25 มี 3,565 วินาที

## ข้อ 5 11:11:11

In [ ]:
time5 = '11:11:11'
time5.split(':')
list_e = time5.split(':')
print(list_e)

['11', '11', '11']


In [ ]:
list_e[0] 
int(list_e[0]) * 3600

39600

In [ ]:
A = int(list_e[0]) * 3600

In [ ]:
list_e[1] 
int(list_e[1]) * 60

660

In [ ]:
B = int(list_e[1]) * 60

In [ ]:
list_e[2]
c = list_e[2]
print(c)

11


In [ ]:
A+B+int(c)

40271

ตอบ 11:11:11 มี 40,271 วินาที

## ข้อ 6 16:06:09

In [ ]:
time6 = '16:06:09'
time6.split(':')
list_g = time6.split(':')
print(list_g)

['16', '06', '09']


In [ ]:
list_g[0] 
int(list_g[0]) * 3600

57600

In [ ]:
A = int(list_g[0]) * 3600

In [ ]:
list_g[1] 
int(list_g[1]) * 60

360

In [ ]:
B = int(list_g[1]) * 60

In [ ]:
list_g[2]
c = list_g[2]
print(c)

09


In [ ]:
A+B+int(c)

57969

ตอบ 16:06:09 มี 57,969 วินาที

## HW 3

In [ ]:
def time(Time) :
  timeall = Time.split(':')
  
  h = int(timeall[0])*3600
  m = int(timeall[1])*60
  s = int(timeall[2])
  all = h+m+s
  SUM = f'{Time} คิดเป็นวินาทีได้ = {all} วินาที'
  print(SUM)

In [ ]:
time('12:30:15')
time('13:41:07')
time('12:53:15')
time('00:59:25')
time('11:11:11')
time('16:06:09')

12:30:15 คิดเป็นวินาทีได้ = 45015 วินาที
13:41:07 คิดเป็นวินาทีได้ = 49267 วินาที
12:53:15 คิดเป็นวินาทีได้ = 46395 วินาที
00:59:25 คิดเป็นวินาทีได้ = 3565 วินาที
11:11:11 คิดเป็นวินาทีได้ = 40271 วินาที
16:06:09 คิดเป็นวินาทีได้ = 57969 วินาที


In [ ]:
list_time = ['12:30:15' , '13:41:07' , '12:53:15' , '00:59:25' , '11:11:11' , '16:06:09']

In [ ]:
for i in list_time :
  time(i)

12:30:15 คิดเป็นวินาทีได้ = 45015 วินาที
13:41:07 คิดเป็นวินาทีได้ = 49267 วินาที
12:53:15 คิดเป็นวินาทีได้ = 46395 วินาที
00:59:25 คิดเป็นวินาทีได้ = 3565 วินาที
11:11:11 คิดเป็นวินาทีได้ = 40271 วินาที
16:06:09 คิดเป็นวินาทีได้ = 57969 วินาที


## โจทย์ HW 4

เขียน function ตัดเกรดโดยที่ input เป็นคะแนน(0-100) ,output เป็นเกรด (F-A) วนลูปตัดเกรด input = [1,50,65,90,101,-5,49]
กำหนด \\
ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 0 แต่น้อยกว่า 50 จะได้เกรด F \\
ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 50 แต่น้อยกว่า 55 จะได้เกรด D \\
ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 55 แต่น้อยกว่า 60 จะได้เกรด D+ \\
ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 60 แต่น้อยกว่า 65 จะได้เกรด C \\
ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 65 แต่น้อยกว่า 70 จะได้เกรด C+ \\
ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 70 แต่น้อยกว่า 75 จะได้เกรด B \\
ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 75 แต่น้อยกว่า 80 จะได้เกรด B+ \\
ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 80 จะได้เกรด A \\
แต่ว่าค่าคะแนนจะต้องไม่ต่ำกว่า 0 และมากกว่า 100 ไม่งั้นจะเกิด error \\

In [ ]:
def grade(score) :
  if score < 0 :
    print(f'ERROR! กรุณากรอกคะแนนใหม่')
  if score >= 0 and score < 50 :
    print(f'คุณมีคะแนนเท่ากับ {score} จะได้เกรด F')
  if score >= 50 and score < 55 :
    print(f'คุณมีคะแนนเท่ากับ {score} จะได้เกรด D')
  if score >= 55 and score < 60 :
    print(f'คุณมีคะแนนเท่ากับ {score} จะได้เกรด D+')
  if score >= 60 and score < 65 :
    print(f'คุณมีคะแนนเท่ากับ {score} จะได้เกรด C')
  if score >= 65 and score < 70 :
    print(f'คุณมีคะแนนเท่ากับ {score} จะได้เกรด C+')
  if score >= 70 and score < 75 :
    print(f'คุณมีคะแนนเท่ากับ {score} จะได้เกรด B')
  if score >= 75 and score < 80 :
    print(f'คุณมีคะแนนเท่ากับ {score} จะได้เกรด B+')
  if score >= 80 and score < 100 :
    print(f'คุณมีคะแนนเท่ากับ {score} จะได้เกรด A')
  if score >= 100 :
    print(f'ERROR! กรุณากรอกคะแนนใหม่')

In [ ]:
sco = [1,50,65,90,101,-5,49]

In [ ]:
for score in sco :
  grade(score)

คุณมีคะแนนเท่ากับ 1 จะได้เกรด F
คุณมีคะแนนเท่ากับ 50 จะได้เกรด D
คุณมีคะแนนเท่ากับ 65 จะได้เกรด C+
คุณมีคะแนนเท่ากับ 90 จะได้เกรด A
ERROR! กรุณากรอกคะแนนใหม่
ERROR! กรุณากรอกคะแนนใหม่
คุณมีคะแนนเท่ากับ 49 จะได้เกรด F


## HW 5

เขียน function คูณ matrix  \\
แล้ว test กับ matrix ขนาด \\
(2,3) * (3,2) \\
(4,4) * (4,1) \\
(2,2) * (2,2)

In [1]:
import numpy 

In [2]:
matrix1_array = numpy.array([[3,8], [1,9]])
print(matrix1_array)

[[3 8]
 [1 9]]


In [3]:
matrix2_array = numpy.array([[4,5], [2,6]])
print(matrix2_array)

[[4 5]
 [2 6]]


In [4]:
matrix23_array = numpy.array([[2,3,5],[1,8,6]])
print(matrix23_array)

[[2 3 5]
 [1 8 6]]


In [5]:
matrix32_array = numpy.array([[7,5],[8,3],[4,2]])
print(matrix32_array)

[[7 5]
 [8 3]
 [4 2]]


In [6]:
matrix44_array = numpy.array([[7,1,3,9], [4,2,1,8], [2,1,4,1], [1,5,4,2]])
print(matrix44_array)

[[7 1 3 9]
 [4 2 1 8]
 [2 1 4 1]
 [1 5 4 2]]


In [7]:
matrix41_array = numpy.array([[9], [8], [6], [4]])
print(matrix41_array)

[[9]
 [8]
 [6]
 [4]]


In [8]:
def cal_matrix(a,b) :
  c = [[0 for row in range(len(b[0]))] for col in range(len(a))]
  for d in range(len(a)) :
    for e in range(len(b[0])) :
      for g in range(len(b)) :
        c[d][e] += a[d][g]*b[g][e]
  sum = numpy.matrix(c)
  return sum

In [9]:
cal_matrix(matrix23_array,matrix32_array)

matrix([[58, 29],
        [95, 41]])

In [10]:
cal_matrix(matrix44_array,matrix41_array)

matrix([[125],
        [ 90],
        [ 54],
        [ 81]])

In [11]:
cal_matrix(matrix1_array,matrix2_array)

matrix([[28, 63],
        [22, 59]])

## ให้สร้างฟังก์ชั่นคำนวณ

def time(Time) :
list_Time = Time.split(':')
H
  return st

In [ ]:
def time(Time) :
  timeall = Time.split(':')
  
  h = int(timeall[0])*3600
  m = int(timeall[1])*60
  s = int(timeall[2])
  all = h+m+s
  SUM = f'{Time} คิดเป็นวินาทีได้ = {all} วินาที'
  print(SUM)
   

In [ ]:
time('12:30:15')
time('13:41:07')
time('12:53:15')
time('00:59:25')
time('11:11:11')
time('16:06:09')

12:30:15 คิดเป็นวินาทีได้ = 45015 วินาที
13:41:07 คิดเป็นวินาทีได้ = 49267 วินาที
12:53:15 คิดเป็นวินาทีได้ = 46395 วินาที
00:59:25 คิดเป็นวินาทีได้ = 3565 วินาที
11:11:11 คิดเป็นวินาทีได้ = 40271 วินาที
16:06:09 คิดเป็นวินาทีได้ = 57969 วินาที
